### ISSUE TITLE
Many provider are empty

### ISSUE THREAD

**Issue by p1d1d1** [FHNW-IVGI/Geoharvester#113] opened 2024-09-03 07:35 UTC
BUND, GE, GL, GR, JU, SO, SZ, TI, VD, UR, ZG, ZH, ST_SH, ST_BE are all empty.
Please fix this with high priority.

**Comment by p1d1d1** [comment] 2024-09-09 11:52
@FStriewski @314a can u please provide a feedback here?

**Comment by FStriewski** [comment] 2024-09-10 07:04
@eliaferrari We are using the manually processed merged_data.pkl from temp_data - could it be that it was created with an incomplete source.csv?

**Comment by eliaferrari** [comment] 2024-09-11 09:09
> @eliaferrari We are using the manually processed merged_data.pkl from temp_data - could it be that it was created with an incomplete source.csv?

@FStriewski the manually processed dataframe contains all the data, Bund, GE, GL, GR, JU, SO, SZ, TI, VD, UR, ZG, ZH included (https://github.com/FHNW-IVGI/Geoharvester/blob/main/scraper/temp_data/merged_data.pkl). What is missing are the ST_* data, I'll check what the problem is.

You have to replace the old dataframe with this one, otherwise it won't be read in this temporary path with the current code.
As an alternative we can temporary change the path here: https://github.com/FHNW-IVGI/Geoharvester/blob/2f6926e9e45644f7a52d35255b4093c05ad6f79a/server/app/main.py#L78

**Comment by FStriewski** [comment] 2024-09-11 10:08
@eliaferrari Yo're right, I had copied the merged_data.pkl to the data folder on production but the change wasn't picked up. I've adjusted the path now so that we use the temp_data folder for now - in case that we need further manual preprocessing.


Running the scraper now. If you need to test your commits, you can trigger the scraper yourself from this page:
https://github.com/FHNW-IVGI/Geoharvester/actions/workflows/run_scraper.yml 
Klick "Run Workflow" dropdown, check that "main" is selected and click the "Run workflow" Button. You can click on the title of a row to see the pipeline and logs. 


@p1d1d1 Providers should be restored now.

**Comment by p1d1d1** [comment] 2024-09-11 11:25
@FStriewski ST_ZH, ST_BE,ASIT and SOSM are empty

**Comment by eliaferrari** [comment] 2024-09-11 11:47
Indeed the one that I used do not contain ST_ZH, ST_BE, ASIT and SOSM data, I'll process and integrate the missing data locally.
Here we should have all the new datasets: https://github.com/FHNW-IVGI/Geoharvester/blob/main/scraper/sources.csv

**Comment by FStriewski** [comment] 2024-09-11 12:12
This one is the newest version (and the path that is used for the pipline scraper:
https://github.com/FHNW-IVGI/Geoharvester/blob/main/scraper/sources.csv

**Closed** 2024-09-19 08:14 UTC
Labels: bug
